name: Deploy To Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Keys
        run:  |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          sed -i 's/\r$//' ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup .env File
        run:  echo "${{ secrets.ENV_FILE }}" | base64 -d > ~/.env

      - name: Remove existing source code from Server
        run:  |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "cd ~/backend && sudo docker-compose down" || true
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "cd ~/backend && find . -mindepth 1 ! -name 'db.sqlite3' ! -path './src' ! -path './src/*' -delete"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "cd ~/backend && find ./src -mindepth 1 ! -name 'db.sqlite3' -delete"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "cd ~/backend && sudo docker system prune -f"

      - name: Check for db.sqlite3 after deletion
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "ls -l ~/backend/src/db.sqlite3"

      - name: Copy source code to Server
        run:  scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r * .dockerignore ubuntu@${{ secrets.SERVER_HOST }}:~/backend

      - name: Copy .env File to Server
        run:  |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "cd ~/backend/src/dev && mkdir -p ./config"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ~/.env ubuntu@${{ secrets.SERVER_HOST }}:~/backend/src/dev/config

      - name: Run and Build Docker Container
        run:  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} "cd ~/backend && sudo docker-compose up -d --build"